theme: jekyll-theme-slate

title: The Renegade Coder Newsletter
description: A signup form for The Renegade Coder Newsletter.

google_analytics: UA-97956707-4

image_path: /assets/images/
title_image: the-renegade-coder-newsletter-featured-image.JPEG
